//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelperTools.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelperTools.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error: {0}.
        /// </summary>
        public static string ExceptionDialogDefaultText {
            get {
                return ResourceManager.GetString("ExceptionDialogDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string ExceptionDialogDefaultTitle {
            get {
                return ResourceManager.GetString("ExceptionDialogDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file: {0}.
        /// </summary>
        public static string ExceptionDialogFileAccessText {
            get {
                return ResourceManager.GetString("ExceptionDialogFileAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing file.
        /// </summary>
        public static string ExceptionDialogFileAccessTitle {
            get {
                return ResourceManager.GetString("ExceptionDialogFileAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled before completion!.
        /// </summary>
        public static string MessageDialogCancelContent {
            get {
                return ResourceManager.GetString("MessageDialogCancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation!.
        /// </summary>
        public static string MessageDialogCancelTitle {
            get {
                return ResourceManager.GetString("MessageDialogCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully. {0} {0} If the files appear ?.
        /// </summary>
        public static string MessageDialogCompleteContent {
            get {
                return ResourceManager.GetString("MessageDialogCompleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        public static string MessageDialogCompleteTitle {
            get {
                return ResourceManager.GetString("MessageDialogCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has been selected for processing..
        /// </summary>
        public static string NothingToDoDialogText {
            get {
                return ResourceManager.GetString("NothingToDoDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected for processing!.
        /// </summary>
        public static string NothingToDoDialogTitle {
            get {
                return ResourceManager.GetString("NothingToDoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the desired folder..
        /// </summary>
        public static string OpenFolderDescription {
            get {
                return ResourceManager.GetString("OpenFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing is prepared ....
        /// </summary>
        public static string ProgressDialogPreviewContent {
            get {
                return ResourceManager.GetString("ProgressDialogPreviewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are already {0} of {1} files processed..
        /// </summary>
        public static string ProgressDialogRunningContent {
            get {
                return ResourceManager.GetString("ProgressDialogRunningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected data is currently being processed ....
        /// </summary>
        public static string ProgressDialogText {
            get {
                return ResourceManager.GetString("ProgressDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data are processed.
        /// </summary>
        public static string ProgressDialogTitle {
            get {
                return ResourceManager.GetString("ProgressDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processing of {0} files is completed. {1}{1} Should the files displaying?.
        /// </summary>
        public static string ProgressFinishedDialogText {
            get {
                return ResourceManager.GetString("ProgressFinishedDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed.
        /// </summary>
        public static string ProgressFinishedDialogTitle {
            get {
                return ResourceManager.GetString("ProgressFinishedDialogTitle", resourceCulture);
            }
        }
    }
}
