//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelperTools.SharedModules.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelperTools.SharedModules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _Path.
        /// </summary>
        public static string ButtonSelectPath {
            get {
                return ResourceManager.GetString("ButtonSelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _all.
        /// </summary>
        public static string DataGridFilesButtonSelectAll {
            get {
                return ResourceManager.GetString("DataGridFilesButtonSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecet _none.
        /// </summary>
        public static string DataGridFilesButtonSelectNone {
            get {
                return ResourceManager.GetString("DataGridFilesButtonSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string DataGridFilesHeaderChanged {
            get {
                return ResourceManager.GetString("DataGridFilesHeaderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string DataGridFilesHeaderName {
            get {
                return ResourceManager.GetString("DataGridFilesHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string DataGridFilesHeaderSize {
            get {
                return ResourceManager.GetString("DataGridFilesHeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} files selected.
        /// </summary>
        public static string DataGridFilesStatusBarText {
            get {
                return ResourceManager.GetString("DataGridFilesStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated the file list.
        /// </summary>
        public static string StatusBarFileCollectionChanged {
            get {
                return ResourceManager.GetString("StatusBarFileCollectionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all files selected.
        /// </summary>
        public static string StatusBarSelectAll {
            get {
                return ResourceManager.GetString("StatusBarSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changed the working path.
        /// </summary>
        public static string StatusBarSelectedPathChanged {
            get {
                return ResourceManager.GetString("StatusBarSelectedPathChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all files unselected.
        /// </summary>
        public static string StatusBarSelectNone {
            get {
                return ResourceManager.GetString("StatusBarSelectNone", resourceCulture);
            }
        }
    }
}
