//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelperTools.MatFileGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelperTools.MatFileGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto.
        /// </summary>
        public static string CheckBoxAuto {
            get {
                return ResourceManager.GetString("CheckBoxAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inner border.
        /// </summary>
        public static string CheckBoxBorderInner {
            get {
                return ResourceManager.GetString("CheckBoxBorderInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outer frame.
        /// </summary>
        public static string CheckBoxBorderOuter {
            get {
                return ResourceManager.GetString("CheckBoxBorderOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type glass.
        /// </summary>
        public static string CheckBoxGlass {
            get {
                return ResourceManager.GetString("CheckBoxGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mirror.
        /// </summary>
        public static string CheckBoxMirror {
            get {
                return ResourceManager.GetString("CheckBoxMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rauto.
        /// </summary>
        public static string CheckBoxRauto {
            get {
                return ResourceManager.GetString("CheckBoxRauto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ref.
        /// </summary>
        public static string CheckBoxRef {
            get {
                return ResourceManager.GetString("CheckBoxRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate (x/y/z).
        /// </summary>
        public static string CheckBoxRotate {
            get {
                return ResourceManager.GetString("CheckBoxRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scale (x/y/z).
        /// </summary>
        public static string CheckBoxScale {
            get {
                return ResourceManager.GetString("CheckBoxScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shi.
        /// </summary>
        public static string CheckBoxShi {
            get {
                return ResourceManager.GetString("CheckBoxShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create thumb.
        /// </summary>
        public static string CheckBoxThumb {
            get {
                return ResourceManager.GetString("CheckBoxThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tra.
        /// </summary>
        public static string CheckBoxTra {
            get {
                return ResourceManager.GetString("CheckBoxTra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string GroupSettings {
            get {
                return ResourceManager.GetString("GroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        public static string GroupThumbnails {
            get {
                return ResourceManager.GetString("GroupThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color name:.
        /// </summary>
        public static string LabelColorName {
            get {
                return ResourceManager.GetString("LabelColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder:.
        /// </summary>
        public static string LabelThumb {
            get {
                return ResourceManager.GetString("LabelThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat-Files-Generator.
        /// </summary>
        public static string MatFileGenTitle {
            get {
                return ResourceManager.GetString("MatFileGenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} checked.
        /// </summary>
        public static string StatusBarChecked {
            get {
                return ResourceManager.GetString("StatusBarChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mat files generated.
        /// </summary>
        public static string StatusBarFilesGenerated {
            get {
                return ResourceManager.GetString("StatusBarFilesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unchecked.
        /// </summary>
        public static string StatusBarUnchecked {
            get {
                return ResourceManager.GetString("StatusBarUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _2. Solid.
        /// </summary>
        public static string TabItemSolid {
            get {
                return ResourceManager.GetString("TabItemSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _1. Texture.
        /// </summary>
        public static string TabItemTexture {
            get {
                return ResourceManager.GetString("TabItemTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color as HEX:.
        /// </summary>
        public static string TextBlockColorHex {
            get {
                return ResourceManager.GetString("TextBlockColorHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color as RGB:.
        /// </summary>
        public static string TextBlockColorRgb {
            get {
                return ResourceManager.GetString("TextBlockColorRgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a color.
        /// </summary>
        public static string TextBlockColorSelection {
            get {
                return ResourceManager.GetString("TextBlockColorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview image.
        /// </summary>
        public static string TitlePreviewImage {
            get {
                return ResourceManager.GetString("TitlePreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Thumbnail.
        /// </summary>
        public static string TitlePreviewThumbnail {
            get {
                return ResourceManager.GetString("TitlePreviewThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic texture generation on a general rectangular area..
        /// </summary>
        public static string ToolTipAuto {
            get {
                return ResourceManager.GetString("ToolTipAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings for the inner frame of the preview picture..
        /// </summary>
        public static string ToolTipBorderInner {
            get {
                return ResourceManager.GetString("ToolTipBorderInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings for the outer frame of the preview picture..
        /// </summary>
        public static string ToolTipBorderOuter {
            get {
                return ResourceManager.GetString("ToolTipBorderOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify in pixels.
        /// </summary>
        public static string ToolTipBorderSize {
            get {
                return ResourceManager.GetString("ToolTipBorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a simple paint, the color as a hex value can be entered here..
        /// </summary>
        public static string ToolTipColorHex {
            get {
                return ResourceManager.GetString("ToolTipColorHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the color value in the form &quot;#112233&quot;!.
        /// </summary>
        public static string ToolTipColorHexInput {
            get {
                return ResourceManager.GetString("ToolTipColorHexInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the color name (without extension).
        /// </summary>
        public static string ToolTipColorName {
            get {
                return ResourceManager.GetString("ToolTipColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a simple polish the RGB color value can be entered here (from 0 to 255)..
        /// </summary>
        public static string ToolTipColorRgb {
            get {
                return ResourceManager.GetString("ToolTipColorRgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a simple paint, the color value can be selected here..
        /// </summary>
        public static string ToolTipColorSelection {
            get {
                return ResourceManager.GetString("ToolTipColorSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describes whether a material made of glass. The values 0 and 1 are possible..
        /// </summary>
        public static string ToolTipGlass {
            get {
                return ResourceManager.GetString("ToolTipGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the mirror surface. Possible values 0 and 1. 1 means full mirroring; 0.5 could be used for example for high-gloss lacquer front..
        /// </summary>
        public static string ToolTipMirror {
            get {
                return ResourceManager.GetString("ToolTipMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling of the texture to the size of the whole area..
        /// </summary>
        public static string ToolTipRauto {
            get {
                return ResourceManager.GetString("ToolTipRauto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &quot;ref&quot; specifies the refraction through a positive floating point number. The initial refraction has a value of 1.0 and the refraction value vacuum..
        /// </summary>
        public static string ToolTipRef {
            get {
                return ResourceManager.GetString("ToolTipRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the JPG. Here only the Z axis is interesting. The values in the X and y axes remain to 0..
        /// </summary>
        public static string ToolTipRotate {
            get {
                return ResourceManager.GetString("ToolTipRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this, the scale is changed. Required this is of course only when working with textures. The individual values indicate how often the JPG per meter is shown (values are X, Y, and Z)..
        /// </summary>
        public static string ToolTipScale {
            get {
                return ResourceManager.GetString("ToolTipScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &quot;shi&quot; specifies the spekularen exponent by a positive floating point number. The higher is the exponent, the less is the spread of the spekularen highlights. The initial exponent is 30.0..
        /// </summary>
        public static string ToolTipShi {
            get {
                return ResourceManager.GetString("ToolTipShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a thumbnail in the dimensions 50 x 25 pixels. This is stored in the specified folder..
        /// </summary>
        public static string ToolTipThumb {
            get {
                return ResourceManager.GetString("ToolTipThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &quot;tra&quot; specifies the transparency by a non-negative floating point number &lt;=1. Value of 0.0 indicates total impermeability; a value of 1.0 means total transparency. The initial value is 0.0..
        /// </summary>
        public static string ToolTipTra {
            get {
                return ResourceManager.GetString("ToolTipTra", resourceCulture);
            }
        }
    }
}
