//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelperTools.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelperTools.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_shd {
            get {
                object obj = ResourceManager.GetObject("icon_shd", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo_shd_bitmap {
            get {
                object obj = ResourceManager.GetObject("logo_shd_bitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;!--This file is compatible with Silverlight--&gt;
        ///&lt;Canvas xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        Name=&quot;svg3336&quot;
        ///        Width=&quot;176.25&quot;
        ///        Height=&quot;62.5&quot;&gt;
        ///    &lt;Canvas.RenderTransform&gt;
        ///        &lt;TranslateTransform X=&quot;0&quot;
        ///                            Y=&quot;0&quot; /&gt;
        ///    &lt;/Canvas.RenderTransform&gt;
        ///    &lt;Canvas.Resources /&gt;
        ///    &lt;!--Unknown tag: metadata--&gt;
        ///    &lt;!--Unknown tag: sodipodi:namedview--&gt;
        ///    &lt;Path xmlns:x=&quot;http://schemas.microsoft.com/wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string logo_shd_xaml {
            get {
                return ResourceManager.GetString("logo_shd_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string SettingsChangelog {
            get {
                return ResourceManager.GetString("SettingsChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application base.
        /// </summary>
        public static string SettingsGroupApplication {
            get {
                return ResourceManager.GetString("SettingsGroupApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string SettingsGroupInformation {
            get {
                return ResourceManager.GetString("SettingsGroupInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string SettingsTextBlockColor {
            get {
                return ResourceManager.GetString("SettingsTextBlockColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsTextBlockLanguage {
            get {
                return ResourceManager.GetString("SettingsTextBlockLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string SettingsTextBlockTheme {
            get {
                return ResourceManager.GetString("SettingsTextBlockTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SplashScreen {
            get {
                object obj = ResourceManager.GetObject("SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color changed to .
        /// </summary>
        public static string StatusBarAccentColorChanged {
            get {
                return ResourceManager.GetString("StatusBarAccentColorChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed language to .
        /// </summary>
        public static string StatusBarLanguageChanged {
            get {
                return ResourceManager.GetString("StatusBarLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last activity:.
        /// </summary>
        public static string StatusBarLastActivity {
            get {
                return ResourceManager.GetString("StatusBarLastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme changed to .
        /// </summary>
        public static string StatusBarThemeChanged {
            get {
                return ResourceManager.GetString("StatusBarThemeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string StatusBarVersion {
            get {
                return ResourceManager.GetString("StatusBarVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to search for updates has gone wrong.{0}{0}Please try again later or give the creators know.{0}{0}Thank you!.
        /// </summary>
        public static string UpdateErrorDialogText {
            get {
                return ResourceManager.GetString("UpdateErrorDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Adjustment not possible!.
        /// </summary>
        public static string UpdateErrorDialogTitle {
            get {
                return ResourceManager.GetString("UpdateErrorDialogTitle", resourceCulture);
            }
        }
    }
}
